{% set name = "django-filter" %}
{% set version = "23.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-filter-{{ version }}.tar.gz
  sha256: 2fe15f78108475eda525692813205fa6f9e8c1caf1ae65daa5862d403c6dbf00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.7
    - django >=3.2

test:
  imports:
    - django_filters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/carltongibson/django-filter/tree/main
  summary: Django-filter is a reusable Django application for allowing users to filter querysets dynamically.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - https://gb119.github.com/
